12/lab12/config/routes.rb
Rails.application.routes.draw do
  get 'index/output', as: 'output'
  post 'session/login'
  get 'session/logout'
  get 'session/login'
  post 'session/create'

  root 'index#input'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

12/lab12/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :username, message: 'Имя пользователя уже существует'
  validates_presence_of :username, message: 'Имя пользователя не должно быть пустым'
  validates_presence_of :password, message: 'Пароль пользователя не должно быть пустым'
  validates_confirmation_of :password
end

12/lab12/app/controllers/index_controller.rb
# frozen_string_literal: true

require 'prime'

# Контроллер с 8 лабы, ничего нового здесь нет

# Controller for app
class IndexController < ApplicationController
  def input; end

  def output
    @input = params[:inpt]
    if !/^-?\d+$/.match(@input)
      flash[:notice] = 'Введено не число'
    elsif !(@input = @input.to_i).positive?
      flash[:notice] = 'Введено отрицательное число'
    else
      @result = twins(@input)
      return @prime_arr = (@input..2 * @input).select(&:prime?)
    end
    redirect_to :input
  end

  private

  # rubocop:disable Naming/MethodParameterName
  def twins(n)
    arr = []
    primes = (n..2 * n).to_a.select(&:prime?)
    (primes.length - 1).times do |i|
      arr << [primes[i], primes[i + 1]] if primes[i + 1] - primes[i] == 2
    end
    return arr unless arr.length.zero?

    nil
  end
  # rubocop:enable Naming/MethodParameterName
end

12/lab12/app/controllers/session_controller.rb
# frozen_string_literal: false

# Контроллер сессии - время между "пользователь вошел" и "вышел"
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]
  # перекус учителя чекни application_controller.rb
  # Так как все контроллеры наследуются от ApplicationController,
  # то перед каждым вызываем проверку на аутентификация,
  # здесь кроме метода логина, а то будет бексонечный редирект
  # и созданию пользователей, все могут создавать их

  def login; end
  # Только отрисовка формы

  def create
    user = User.find_by_username(params[:username])
    if user&.authenticate(params[:password])
      # authenticate - метод,который сверяет зашифрованный пароль в базе с данным
      # доступен из-за has_secure_password в model/user.rb
      # В gemfile подключить bcrypt
      # user&.auth.. <=> !user.nil? && user.auth...
      # А то скажет no usch method authenticate for nil class
      sign_in user # Наш метод входа, описанный в хелпере
      redirect_to root_url
    else
      flash[:notice] = if user.nil?
                         I18n.t(:invalid_login)
                       else
                         I18n.t(:invalid_password)
                       end
      redirect_to session_login_url
    end
  end

  def logout
    sign_out # Наш метод выхода, описанный в хелпере
    redirect_to session_login_url
  end
end

12/lab12/app/controllers/users_controller.rb
# frozen_string_literal: false

# все сгенерировал rails g scaffold user username:string password_digest:string
# !!!!написать password_!!digest!!, а то не будет работать has_secure_password
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[create new]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user # Если юзер успешно создался, записиываем значение в куки и делаем текущим его пользователем сесии
        format.html { redirect_to root_path, notice: 'Пользователь успешно создан!' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'Пользователь успешно обновлён!' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Пользователь успешно уничтожен!.' }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    # поменять :password_digest на :password, так же в views/users/_form.html.erb
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

12/lab12/app/helpers/session_helper.rb
# frozen_string_literal: false

# Its a very good helper
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 7.days }
    # signed шифрует id пользователя, добавляем срок годности куки, чтобы пользователя не выкидывало во время сессии
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
    # ||= <=> @current_user = User.find if @current_user.nil?
  end
end

12/lab12/app/views/index/input.html.erb
<h1>Введите целое число n > 0</h1>
<%unless flash[:notice].blank?%>
  <h2 style = 'color:red'><%=flash[:notice]%></h2>
<%end%>

<%= form_with url: :output, method: :get do |form| %>
  <%= form.number_field :inpt, in:1..Float::INFINITY%>
  <%= form.submit "Отправить", id: 'submit-btn' %>
<% end %>
<%=link_to 'Выйти из учетной записи', session_logout_path%>
<%=link_to 'Просмотреть базу с пользователями', :users%>

12/lab12/app/views/index/output.html.erb
<h2>Вы ввели</h2>
<p><%=@input%></p>

<%unless @result.nil?%>

<h2>Простые числа в диапазоне от <%="#{@input} до #{@input * 2}"%></h2>
<table>
    <tr>
      <td colspan = 2 >Соседние числа</td>
      <td>Разница <br/> между ними</td>
    </tr>
  <%(@prime_arr.length - 1).times do |i|%>
    <tr>
      <td><%=@prime_arr[i]%></td>
      <td><%=@prime_arr[i + 1]%></td>
      <%=content_tag(:td, "#{diff = @prime_arr[i + 1] - @prime_arr[i]}", :class => ( (diff) == 2 ? 'right' : 'wrong') )%>
    </tr>
    <%end%>

</table>

<h2>Результат</h2>
  <table id = 'result'>
  <tr>
    <td colspan = 2>Числа близнецы</td>
  </tr>
  <%@result.each do |i|%>
    <tr>
      <td><%=i[0]%></td>
      <td><%=i[1]%></td>
    </tr>
    <%end%>
</table>
<%else%><p>Для данного n нет близнецов в диапазоне от n до 2n</p>
<%end%>
<br/>
<%=link_to 'Вернуться','input'%><br/>

12/lab12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-turbo='false'>
  <head>
    <title>Lab12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

12/lab12/app/views/session/login.html.erb
<%unless flash[:notice].blank?%>
  <h2 style = 'color:red'><%=flash[:notice]%></h2>
<%end%>

<%=form_with url: session_create_url, method: :post, local:true do |f|%>
	<table id='login'>
		<tr>
			<td><label>Имя пользователя</label></td>
			<td><%=f.text_field :username, require: true %><br/></td>
		</tr>
		<tr>
			<td><label>Пароль</label></td>
			<td><%=f.password_field :password, require: true%><br/></td>
		</tr>
		<tr>
			<td><%=f.submit id: 'submit-btn', value: 'Вход',require: true%></td>
		</tr>
	</table>
<%end%>

<%=link_to 'Регистрация', new_user_path%>

12/lab12/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2>Пользователь не был создан:</h2>

      <ul>
        <% user.errors.each do |error| %>
        <% p error%>
          <li><%= error.full_message%></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, value: 'Имя пользователя',style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, value: 'Пароль', style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :lbl, value: 'Подтвердите пароль', style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit 'Создать', id: 'submit-btn'%>
  </div>
<% end %>